In [10]:
import pandas as pd
import numpy as np

from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import NearestNeighbors

In [11]:
data = pd.read_csv('datasets/iz4_table.csv')
data

id   X   Y  Class
0   1  56  82      1
1   2  96  36      0
2   3  78  73      1
3   4  69  19      1
4   5  12  44      1
5   6  77  32      0
6   7  55  38      1
7   8  86  95      1
8   9  46  99      1
9  10  15  83      0

In [69]:
X = np.array([data['X'], data['Y']])
X = np.reshape(X, 20, order='F')
X = np.reshape(X, [10,2])
X

array([[56, 82],
       [96, 36],
       [78, 73],
       [69, 19],
       [12, 44],
       [77, 32],
       [55, 38],
       [86, 95],
       [46, 99],
       [15, 83]], dtype=int64)

In [98]:
y = np.array([[17]*10, [94]*10])
y = np.reshape(y, 20, order='F')
y = np.reshape(y, [10, 2])
y

array([[17, 94],
       [17, 94],
       [17, 94],
       [17, 94],
       [17, 94],
       [17, 94],
       [17, 94],
       [17, 94],
       [17, 94],
       [17, 94]])

In [99]:
knn = NearestNeighbors(n_neighbors=9,	
											 metric='euclidean').fit(X)

In [122]:
dist, ind = knn.kneighbors(y)
dist.min(), ind

(11.180339887498949,
 array([[9, 8, 0, 4, 2, 6, 7, 5, 3],
        [9, 8, 0, 4, 2, 6, 7, 5, 3],
        [9, 8, 0, 4, 2, 6, 7, 5, 3],
        [9, 8, 0, 4, 2, 6, 7, 5, 3],
        [9, 8, 0, 4, 2, 6, 7, 5, 3],
        [9, 8, 0, 4, 2, 6, 7, 5, 3],
        [9, 8, 0, 4, 2, 6, 7, 5, 3],
        [9, 8, 0, 4, 2, 6, 7, 5, 3],
        [9, 8, 0, 4, 2, 6, 7, 5, 3],
        [9, 8, 0, 4, 2, 6, 7, 5, 3]], dtype=int64))

In [129]:
y = np.array(data['Class'])
y

array([1, 0, 1, 1, 1, 0, 1, 1, 1, 0], dtype=int64)

In [139]:
knn = KNeighborsClassifier(n_neighbors=10, p=2)
knn.fit(X, y)

KNeighborsClassifier(n_neighbors=10)

In [140]:
dist, ind = knn.kneighbors([[17, 94]])
dist, ind

(array([[11.18033989, 29.42787794, 40.80441153, 50.24937811, 64.51356447,
         67.67569726, 69.007246  , 86.27861844, 91.26335519, 98.00510191]]),
 array([[9, 8, 0, 4, 2, 6, 7, 5, 3, 1]], dtype=int64))