In [1]:
import torch 

In [2]:
torch.zeros([3, 4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [11]:
x = torch.Tensor([[3, 4, 5],
									[3, 4, 5],
									[3, 4, 5]])

In [14]:
x[0, 0] # x[0][0]

tensor(3.)

In [9]:
torch.exp(x)

tensor([[20.0855, 54.5981],
        [20.0855, 54.5981],
        [20.0855, 54.5981]])

In [12]:
x[x > 3]

tensor([4., 5., 4., 5., 4., 5.])

In [30]:
x = torch.tensor([[1, 2, 3], 
									[4, 5, 6], 
									[7, 8, 9]])
y = x

In [31]:
x = x.double()
x.dtype

torch.float64

In [32]:
x = torch.rand([2, 3])
x

tensor([[0.3727, 0.0849, 0.9224],
        [0.1398, 0.5314, 0.2780]])

In [33]:
torch.cuda.is_available()

False

In [39]:
torch.device('cuda:0')

device(type='cuda', index=0)

In [40]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

In [42]:
x_cuda = x.to(device)
x_cuda

tensor([[0.3727, 0.0849, 0.9224],
        [0.1398, 0.5314, 0.2780]])